# Generated by Django 5.0 on 2023-10-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('invoice_no', models.CharField(default='', max_length=20)),
                ('qty', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NonFixed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('invoice_no', models.CharField(default='', max_length=40)),
                ('qty', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
            ],
        ),
    ]
