# Generated by Django 5.0 on 2023-10-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_fixed_item_name_nonfixed_item_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('invoice_no', models.CharField(default='', max_length=20)),
                ('item_name', models.CharField(default='', max_length=200)),
                ('qty', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='NonFixedAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('type', models.CharField(default='', max_length=50)),
                ('shop_name', models.CharField(default='', max_length=200)),
                ('invoice_no', models.CharField(default='', max_length=40)),
                ('item_name', models.CharField(default='', max_length=200)),
                ('qty', models.IntegerField(default='')),
                ('price', models.IntegerField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Fixed',
        ),
        migrations.DeleteModel(
            name='NonFixed',
        ),
    ]
